import "@ant-design/v5-patch-for-react-19";
import { ReactNode } from "react";

import Providers from "./providers";

// import "antd/dist/reset.css";
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
}

// const rootMap = new WeakMap<Element, Root>();

// unstableSetRender((node, container) => {
//   if (!(container instanceof Element)) {
//     throw new Error("Container is not a valid DOM Element");
//   }

//   let root = rootMap.get(container);
//   if (!root) {
//     root = createRoot(container);
//     rootMap.set(container, root);
//   }
//   root.render(node);

//   return async () => {
//     await new Promise((resolve) => setTimeout(resolve, 0));
//     root?.unmount();
//     rootMap.delete(container);
//   };
// });

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
